export const RFP_STATUS = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  RESPONSES_RECEIVED: 'RESPONSES_RECEIVED',
  EVALUATED: 'EVALUATED',
  AWARDED: 'AWARDED',
  CANCELLED: 'CANCELLED',
};

export const PROPOSAL_STATUS = {
  RECEIVED: 'RECEIVED',
  PARSING: 'PARSING',
  PARSED: 'PARSED',
  EVALUATED: 'EVALUATED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
};